- name: Download cert manager CRDs
  ansible.builtin.get_url:
    url: https://github.com/cert-manager/cert-manager/releases/download/{{ rancher.service.cert_manager_crd_version }}/cert-manager.crds.yaml
    dest: ~/cert-manager.crds.yaml
    mode: '0664'

- name: Install custom cert manager resource definitions
  kubernetes.core.k8s:
    state: present
    src: ~/cert-manager.crds.yaml

- name: Add jetstack repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Deploy {{ cert_manager.service.name }} helm chart
  kubernetes.core.helm:
    name: "{{ cert_manager.service.name }}"
    chart_ref: "jetstack/{{ cert_manager.service.name }}"
    release_namespace: cert-manager
    create_namespace: true
    chart_version: "{{ cert_manager.service.version }}"
    values:
      installCRDs: false

- name: Deploy Cert Manager Issuer
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'deploy.yaml.j2') | from_yaml_all }}"
